"tipesOfWines" = [
    {
        "id": 1,
        "Image" : 1,
        "Nombre": "Double Diamond",
        "Pais": "Estados Unidos",
        "Bandera": "EstadosUnidos",
        "Region": "Oakville",
        "Bodega": "Schrader Cellars",
        "TipoDeVino": "Tinto",
        "Uva" : "Cabernet Sauvignon",
        "Cosecha" : 2019,
        "Puntuación": 94,
        "Precio" : 81.93,
    },
    {
        "id": 2,
        "Image" : 2,
        "Nombre":"Brunello di Montalcino",
        "Pais" : "Italia",
        "Bandera" : "Italia",
        "Region":"Fattoria dei Barbi",
        "Bodega": "Brunello di Montalcino",
        "TipoDeVino":	"Tinto",
        "Uva" : "Sangiovese",
        "Cosecha": 2016,
        "Puntuación": 95,
        "Precio": 125.00,
    },
    {
        "id": 3,
        "Image" : 3,
        "Nombre":"Belle Cousine (Hyde Vineyard)",
        "Pais": "Estados Unidos",
        "Bandera": "EstadosUnidos",
        "Region": "Valle de Napa",
        "Bodega": "HDV",
        "TipoDeVino": "Tinto",
        "Uva" :	"Mezcla",
        "Cosecha": 2019,
        "Puntuación": 98,
        "Precio": 77.36,
    },
    {
        "id": 4,
        "Image" : 4,
        "Nombre": "Saint-Julien (Grand Cru Classé)",
        "Pais": "Francia",
        "Bandera": "Francia",
        "Region": "Saint-Julien",
        "Bodega": "Château Talbot",
        "TipoDeVino":	"Tinto",
        "Uva": "Cabernet Sauvignon",
        "Cosecha": 2019,
        "Puntuación": 95,
        "Precio": 510.35,
    },
    {
        "id": 5,
        "Image" : 5,
        "Nombre": "Tignanello",
        "Pais": "Italia",
        "Bandera": "Italia",
        "Region": "Toscana",
        "Bodega": "Antinori",
        "TipoDeVino": "Tinto",
        "Uva": "Mezcla",
        "Cosecha": 2017,
        "Puntuación": 99,
        "Precio": 128.30,
    },
    {
        "id": 6,
        "Image" : 6,
        "Nombre": "The Estates Cabernet Sauvignon",
        "Pais": "Estados Unidos",
        "Bandera": "EstadosUnidos",
        "Region": "Oakville",
        "Bodega": "Robert Mondavi Winery",
        "TipoDeVino": "Tinto",
        "Uva": "Cabernet Sauvignon",
        "Cosecha": 2019,
        "Puntuación": 94,
        "Precio": 73.60,
    },
    {
        "id":7,
        "Image" : 7,
        "Nombre": "Châteauneuf-du-Pape",
        "Pais": "Francia",
        "Bandera": "Francia",
        "Region": "Châteauneuf-du-Pape",
        "Bodega": "Château de Beaucastel",
        "TipoDeVino": "Tinto",
        "Uva": "Grenache",
        "Cosecha": 2019,
        "Puntuación": 96,
        "Precio": 110.16,
    },
    {
        "id": 8,
        "Image" : 8,
        "Nombre": "Saffredi",
        "Pais": "Italia",
        "Bandera": "Italia",
        "Region": "Maremma Toscana",
        "Bodega": "Fattoria Le Pupille",
        "TipoDeVino": "Tinto",
        "Uva": "Cabernet Sauvignon",
        "Cosecha": 2016,
        "Puntuación": 96,
        "Precio": 101.23,
    },
    {
        "id": 9,
        "Image" : 9,
        "Nombre": "Cabernet Sauvignon",
        "Pais": "Estados Unidos",
        "Bandera": "EstadosUnidos",
        "Region": "Columbia Valley",
        "Bodega": "Quilceda Creek",
        "TipoDeVino": "Tinto",
        "Uva": "Cabernet Sauvignon",
        "Cosecha": 2020,
        "Puntuación": 100,
        "Precio": 182.14,
    },
    {
        "id": 10,
        "Image" : 10,
        "Nombre": "Champagne Cristal",
        "Pais": "Francia",
        "Bandera": "Francia",
        "Region": "Champán",
        "Bodega": "Louis Roederer",
        "TipoDeVino": "Espumoso",
        "Uva": "Pinot Noir",
        "Cosecha": 2008,
        "Puntuación": 100,
        "Precio": 280.00,
    },
    {
        "id": 11,
        "Image" : 11,
        "Nombre": "Saint-Émilion (Premier Grand Cru Classé)",
        "Pais": "Francia",
        "Bandera": "Francia",
        "Region": "Saint-Émilion Grand Cru",
        "Bodega": "Château Beau-Sejour Becot",
        "TipoDeVino": "Tinto",
        "Uva": "Merlot",
        "Cosecha": 2019,
        "Puntuación": 95,
        "Precio": 63.40,
    },
    {
        "id": 12,
        "Image" : 12,
        "Nombre": "Bolgheri Superiore",
        "Pais": "Italia",
        "Bandera": "Italia",
        "Region": "Bolgheri Superiore",
        "Bodega": "Grattamacco",
        "TipoDeVino": "Tinto",
        "Uva": "Mezcla",
        "Cosecha": 2012,
        "Puntuación": 96,
        "Precio": 45.00,
    },
    {
        "id": 13,
        "Image" : 13,
        "Nombre": "Sauvignon Blanc",
        "Pais": "Nueva Zelanda",
        "Bandera": "NuevaZelanda",
        "Region": "Marlborough",
        "Bodega": "Greywacke",
        "TipoDeVino": "Blanco",
        "Uva": "Sauvignon Blanc",
        "Cosecha": 2019,
        "Puntuación": 95,
        "Precio": 19.45,
    },
    {
        "id": 14,
        "Image" : 14,
        "Nombre": "Cabernet Sauvignon",
        "Pais": "Estados Unidos",
        "Bandera": "EstadosUnidos",
        "Region": "Valle de Napa",
        "Bodega": "Philip Togni",
        "TipoDeVino": "Tinto",
        "Uva": "Cabernet Sauvignon",
        "Cosecha": 2001,
        "Puntuación": 95,
        "Precio": 111.95,
    },
    {
        "id": 15,
        "Image" : 15,
        "Nombre": "Chardonnay",
        "Pais": "Estados Unidos",
        "Bandera": "EstadosUnidos",
        "Region": "Eola-Amity Hills",
        "Bodega": "RoseRock",
        "TipoDeVino": "Blanco",
        "Uva": "Chardonnay",
        "Cosecha": 2020,
        "Puntuación": 94,
        "Precio": 41.50,
    },
    {
        "id": 16,
        "Image" : 16,
        "Nombre": "Beautiful Earth White",
        "Pais": "Estados Unidos",
        "Bandera": "EstadosUnidos",
        "Region": "Paso Robles",
        "Bodega": "McPrice Myers",
        "TipoDeVino": "Blanco",
        "Uva": "Grenache Blanc",
        "Cosecha": 2020,
        "Puntuación": 95,
        "Precio": 38.44,
    },
    {
        "id": 17,
        "Image" : 17,
        "Nombre": "Amancaya Gran Reserva Malbec - Cabernet Sauvignon",
        "Pais": "Argentina",
        "Bandera": "Argentina",
        "Region": "Mendoza",
        "Bodega": "Caro (Catena and Rothschild)",
        "TipoDeVino": "Tinto",
        "Uva": "Malbec",
        "Cosecha": 2020,
        "Puntuación": 93,
        "Precio": 21.04,
    },
    {
        "id": 18,
        "Image" : 18,
        "Nombre": "Pinot Noir",
        "Pais": "Australia",
        "Bandera": "Australia",
        "Region": "Yarra Valley",
        "Bodega": "Giant Steps",
        "TipoDeVino": "Tinto",
        "Uva": "Pinot Noir",
        "Cosecha": 2021,
        "Puntuación": 94,
        "Precio": 26.38,
    },
    {
        "id": 19,
        "Image" : 19,
        "Nombre": "Blanc De Blancs Brut",
        "Pais": "Estados Unidos",
        "Bandera": "EstadosUnidos",
        "Region": "Costa Norte",
        "Bodega": "Schramsberg",
        "TipoDeVino": "Espumoso",
        "Uva": "Chardonnay",
        "Cosecha": 2018,
        "Puntuación": 93,
        "Precio": 33.68,
    },
    {
        "id": 20,
        "Image" : 20,
        "Nombre": "Burn Cottage Vineyard Pinot Noir",
        "Pais": "Nueva Zelanda",
        "Bandera": "NuevaZelanda",
        "Region": "Central Otago",
        "Bodega": "Burn Cottage",
        "TipoDeVino": "Tinto",
        "Uva": "Pinot Noir",
        "Cosecha": 2019,
        "Puntuación": 96,
        "Precio": 50.43,
    },
    {
        "id":21,
        "Image" : 21,
        "Nombre": "Cabernet Sauvignon",
        "Pais": "Chile",
        "Bandera": "Chile",
        "Region": "Valle de Colchagua",
        "Bodega": "Montes Alpha",
        "TipoDeVino": "Tinto",
        "Uva": "Cabernet Sauvignon",
        "Cosecha": 2019,
        "Puntuación": 93,
        "Precio": 19.06,
    },
    {
        "id": 22,
        "Image" : 22,
        "Nombre": "Chianti Classico Riserva",
        "Pais": "Italia",
        "Bandera": "Italia",
        "Region": "Chianti Classico",
        "Bodega": "Capraia",
        "TipoDeVino": "Tinto",
        "Uva": "Sangiovese",
        "Cosecha": 2018,
        "Puntuación": 94,
        "Precio": 21.17,
    },
    {
        "id": 23,
        "Image" : 23,
        "Nombre": "Remolinos Vineyard Malbec",
        "Pais": "Argentina",
        "Bandera": "Argentina",
        "Region": "Agrelo",
        "Bodega": "Finca Decero",
        "TipoDeVino": "Tinto",
        "Uva": "Malbec",
        "Cosecha": 2019,
        "Puntuación": 92,
        "Precio": 18.65,
    },
    {
        "id": 24,
        "Image" : 24,
        "Nombre": "Côtes de Provence",
        "Pais": "Francia",
        "Bandera": "Francia",
        "Region": "Côtes de Provence",
        "Bodega": "Fleurs de Prairie",
        "TipoDeVino": "Rosado",
        "Uva": "Grenache",
        "Cosecha": 2020,
        "Puntuación": 92,
        "Precio": 9.95,
    },
    {
        "id": 25,
        "Image" : 25,
        "Nombre": "Ru Rosa de Uva",
        "Pais": "Mexico",
        "Bandera": "Mexico",
        "Region": "Coahuila",
        "Bodega": "Bodegas del Viento",
        "TipoDeVino": "Rosado",
        "Uva": "Mezcla",
        "Cosecha": 2016,
        "Puntuación": 95,
        "Precio": 16.34,
    },
    {
        "id":26,
        "Image" : 26,
        "Nombre": "Pinot Noir",
        "Pais": "Estados Unidos",
        "Bandera": "EstadosUnidos",
        "Region": "Sonoma Valley",
        "Bodega": "Hanzell",
        "TipoDeVino": "Tinto",
        "Uva": "Pinot Noir",
        "Cosecha": 2019,
        "Puntuación": 95,
        "Precio": 91.01,
    },
    {
        "id": 27,
        "Image" : 27,
        "Nombre": "Mother's Milk Shiraz",
        "Pais": "Australia",
        "Bandera": "Australia",
        "Region": "Barossa",
        "Bodega": "First Drop ",
        "TipoDeVino": "Tinto",
        "Uva": "Shiraz/Syrah",
        "Cosecha": 2020,
        "Puntuación": 92,
        "Precio": 17.63,
    },
    {
        "id": 28,
        "Image" : 28,
        "Nombre": "Sauvignon Blanc",
        "Pais":  "Nueva Zelanda",
        "Bandera": "NuevaZelanda",
        "Region": "Marlborough",
        "Bodega": "McBride Sisters",
        "TipoDeVino": "Blanco",
        "Uva": "Sauvignon Blanc",
        "Cosecha": 2021,
        "Puntuación": 91,
        "Precio": 13.38,
    },
    {
        "id": 29,
        "Image" : 29,
        "Nombre": "Alma De Cattleya Sauvignon Blanc",
        "Pais": "Estados Unidos",
        "Bandera": "EstadosUnidos",
        "Region": "Condado de Sonoma",
        "Bodega": "Cattleya",
        "TipoDeVino": "Blanco",
        "Uva": "Sauvignon Blanc",
        "Cosecha": 2021,
        "Puntuación": 92,
        "Precio": 18.18,
    },
    {
        "id": 30,
        "Image" : 30,
        "Nombre": "Blanc De Blancs Brut",
        "Pais": "España",
        "Bandera": "España",
        "Region": "Penedès",
        "Bodega": "Raventós I Blanc",
        "TipoDeVino": "Blanco",
        "Uva": "Macabeo",
        "Cosecha": 2020,
        "Puntuación": 91,
        "Precio": 12.71,
    },
]